name: Deploy Desktop App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build JAR
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Extract version from pom.xml
        id: extract_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Build executable JAR
        run: mvn clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: target/*.jar

  package-exe:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build executable JAR again
        run: mvn clean package -DskipTests

      - name: Use jpackage to create .exe installer
        run: |
          jpackage ^
            --input target ^
            --name MyApp ^
            --main-jar pbo-tubes-1.0-SNAPSHOT.jar ^
            --type exe ^
            --dest dist ^
            --win-dir-chooser ^
            --win-shortcut ^
            --win-menu ^
            --win-menu-group "MyApp Group"
        shell: cmd

      - name: Upload EXE installer
        uses: actions/upload-artifact@v4
        with:
          name: myapp-installer
          path: dist/*.exe

  release:
    runs-on: ubuntu-latest
    needs: [build, package-exe]
    permissions:
      contents: write  # Required to create releases

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myapp-jar
          path: artifacts/

      - uses: actions/download-artifact@v4
        with:
          name: myapp-installer
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          files: |
            artifacts/*.jar
            artifacts/*.exe
