name: Test Coverage and Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Archive JaCoCo XML & HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage
          path: |
            target/site/jacoco/jacoco.xml
            target/site/jacoco/**

      - name: Run SpotBugs analysis
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs --file pom.xml

      - name: Archive SpotBugs XML
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugs/spotbugsXml.xml
