name: Test Coverage and Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: db_j348
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Allow root remote access with empty password
        run: |
          mysql -h127.0.0.1 -uroot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';"
          mysql -h127.0.0.1 -uroot -e "FLUSH PRIVILEGES;"

      - name: Allow root remote access with empty password
        run: |
          mysql -h127.0.0.1 -uroot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';"
          mysql -h127.0.0.1 -uroot -e "FLUSH PRIVILEGES;"

      - name: Run tests with JaCoCo agent
        run: |
          mvn org.jacoco:jacoco-maven-plugin:prepare-agent test --file pom.xml
          mvn org.jacoco:jacoco-maven-plugin:report --file pom.xml

      - name: Archive JaCoCo XML & HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage
          path: |
            target/site/jacoco/jacoco.xml
            target/site/jacoco/**

      - name: Run SpotBugs analysis
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dspotbugs.failOnError=false --file pom.xml

      - name: Archive SpotBugs XML
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugs/spotbugsXml.xml
